SET(CPURAYTRACING_SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/CpuRaytracing)

## HEADERS ##
SET(CPURAYTRACING_HEADERS
    ${CPURAYTRACING_SRC_DIR}/CpuRaytracingCharacter.h
    ${CPURAYTRACING_SRC_DIR}/CpuRaytracingPlay.h)
    

## SOURCES ##
SET(CPURAYTRACING_SOURCES
    ${CPURAYTRACING_SRC_DIR}/CpuRaytracingCharacter.cpp
    ${CPURAYTRACING_SRC_DIR}/CpuRaytracingPlay.cpp)

## Resources ##
QT5_ADD_RESOURCES(CPURAYTRACING_RESOURCES
    ${CPURAYTRACING_SRC_DIR}/resources/CpuRaytracing.qrc)

## GLOBAL ##
SET(CPURAYTRACING_SRC_FILES
    ${CPURAYTRACING_HEADERS}
    ${CPURAYTRACING_SOURCES}
    ${CPURAYTRACING_RESOURCES})
