SET(CPURAYTRACING_SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/CpuRaytracing)

## HEADERS ##
SET(CPURAYTRACING_HEADERS
    ${CPURAYTRACING_SRC_DIR}/CpuRaytracingCharacter.h
    ${CPURAYTRACING_SRC_DIR}/PostProdManager.h
    ${CPURAYTRACING_SRC_DIR}/RaytracedView.h
    ${CPURAYTRACING_SRC_DIR}/RaytracerGui.h)
    

## SOURCES ##
SET(CPURAYTRACING_SOURCES
    ${CPURAYTRACING_SRC_DIR}/CpuRaytracingCharacter.cpp
    ${CPURAYTRACING_SRC_DIR}/PostProdManager.cpp
    ${CPURAYTRACING_SRC_DIR}/RaytracedView.cpp
    ${CPURAYTRACING_SRC_DIR}/RaytracerGui.cpp)

## Resources ##
QT5_ADD_RESOURCES(CPURAYTRACING_RESOURCES
    ${CPURAYTRACING_SRC_DIR}/resources/CpuRaytracing.qrc)

## UI
SET(CPURAYTRACING_UI_FILES
    ${CPURAYTRACING_SRC_DIR}/RaytracerGui.ui)
QT5_WRAP_UI(CPURAYTRACING_UI_SRCS ${CPURAYTRACING_UI_FILES})

## GLOBAL ##
SET(CPURAYTRACING_SRC_FILES
    ${CPURAYTRACING_HEADERS}
    ${CPURAYTRACING_SOURCES}
    ${CPURAYTRACING_RESOURCES}
    ${CPURAYTRACING_UI_FILES}
    ${CPURAYTRACING_UI_SRCS})
