# Qt
FIND_PACKAGE(Qt5OpenGL REQUIRED)
SET(CMAKE_AUTOMOC ON)
SET(CMAKE_INCLUDE_CURRENT_DIR ON)

# ExTh
SET(CMAKE_MODULE_PATH ${CMAKE_MODULE_PATH} "${EXTH-DEMOS_SRC_DIR}/../ExperimentalTheatre/")
FIND_PACKAGE(ExperimentalTheatre REQUIRED)

#Globals
SET(EXTH-DEMOS_LIBRARIES
    ${ExTh_LIBRARIES})
SET(EXTH-DEMOS_INCLUDE_DIRS
    ${EXTH-DEMOS_INCLUDE_DIRS}
    ${EXTH-DEMOS_SRC_DIR}
    ${ExTh_INCLUDE_DIRS})
SET(EXTH-DEMOS_QT_MODULES
    OpenGL)

