SET(PHYSICS2D_SRC_DIR ${CMAKE_CURRENT_SOURCE_DIR}/Physics2D)

## HEADERS ##
SET(PHYSICS2D_HEADERS
    ${PHYSICS2D_SRC_DIR}/Physics2DCharacter.h
    ${PHYSICS2D_SRC_DIR}/Physics2DPlay.h)
    

## SOURCES ##
SET(PHYSICS2D_SOURCES
    ${PHYSICS2D_SRC_DIR}/Physics2DCharacter.cpp
    ${PHYSICS2D_SRC_DIR}/Physics2DPlay.cpp)

## Resources ##
QT5_ADD_RESOURCES(PHYSICS2D_RESOURCES
    ${PHYSICS2D_SRC_DIR}/resources/Physics2D.qrc)

## GLOBAL ##
SET(PHYSICS2D_SRC_FILES
    ${PHYSICS2D_HEADERS}
    ${PHYSICS2D_SOURCES}
    ${PHYSICS2D_RESOURCES})
    
SET(PHYSICS2D_CONFIG_FILES
    ${PHYSICS2D_SRC_DIR}/CMakeLists.txt
    ${PHYSICS2D_SRC_DIR}/FileLists.cmake
    ${PHYSICS2D_SRC_DIR}/LibLists.cmake)
